### ISSUE TITLE
Add Option to display Capital Gain of whole Portfolio/Holdings List

### ISSUE THREAD

**Issue by EarthlingX** [andywuest/harbour-watchlist#105]
Thank you so much for your great app Watchlist! :1st_place_medal: 

In most cases users have added several different stocks into their watchlist. However, in harbour-watchlist it is even possible to create a additional holdings list independent of the watchlist.

I would really much appreciate an option to display the current capital gain of my overall holdings portfolio. Let's have a look at an example.

**Assumed we have the following stocks in our holdings portfolio:**

- Security 1 with share value of 5000 EUR
- Security 2 with share value of 2000 EUR

Now, let's say, during the day stock 1 will increase its value by 2 % while stock 2 will decrease its value by 1 %.

**That means:**

- Security 1 share value will now be 5100 EUR (= increase of +100 EUR)
- Security 2 share value will now be 1990 EUR (= decrease of -20 EUR)

In consideration of this weighed security gain, we got a stock gain of +80 EUR in summary.

80 EUR gain out of 7000 EUR is 1.14 %. So our portfolio has gained value of 1.14 % what could be displayed in harbour-watchlist on a daily basis

Do you think this is possible?

**Comment by andywuest** [comment]
Possible yes - i will have a look. Only the pieces per security needs to be added. The rest is already there.

**Comment by EarthlingX** [comment]
> Possible yes - i will have a look. Only the pieces per security needs to be added. The rest is already there.

Awesome, thank you very much! :+1: 

I think the easiest and perhaps most handy way would be an option to just insert the percentage share of each security of the overall portfolio.

You can have a look at this great backtesting simulator here: https://curvo.eu/backtest/portfolio/new

Example:

- Security 1 has 40 % share of the overall portfolio
- Security 2 has 30 %...
- Security 3 has 30 %

So now we are able to calculate the overall performance of the portfolio (in %) by simply calculating the weighed average of the daily performance changes considering each security.

But well, if we also add the financial value to each security, we are even able to calculate the financial (overall) portfolio performance in EUR. This would be even more awesome.

But I think this would be much more work, no?

**Comment by andywuest** [comment]
Implemented some stuff - now - The performance of the portfolio is now displayed in header - Number of pieces has to be given in the reference price dialog - additional performance information is displayed in stock details. See attached screenshots: 

![Screenshot_20230518_202155](https://github.com/andywuest/harbour-watchlist/assets/644248/3d537d11-8efc-4494-a27d-4e6bf106d955)
![Screenshot_20230518_202346](https://github.com/andywuest/harbour-watchlist/assets/644248/05c32bc2-0550-4f4a-ad6c-01dc97f766af)
![Screenshot_20230518_202414](https://github.com/andywuest/harbour-watchlist/assets/644248/8407757b-2d4f-4160-afc8-cdf2868c92fa)

**Comment by andywuest** [comment]
Implemented.
