### ISSUE TITLE
Add Option to Sort Stock Quotes by Performance

### ISSUE THREAD

**Issue by EarthlingX** [andywuest/harbour-watchlist#107]
Hi Andy,

happy new year! :-)

Currently Watchlist entries (= stock quotes) can be sorted either _by name_ or alternatively _by change_:

![Screenshot_20240104_001](https://github.com/andywuest/harbour-watchlist/assets/38689554/0b03a974-c87a-4967-9da3-f79c649fdbc6)

**Would it be possible to add a third option to sort them _by performance_?**

When sorting by performance, I could directly see which stocks ran great and which did not. :-)

Thank you very much for your efforts!

All the best
EarhlingX

**Comment by andywuest** [comment]
should be an easy change - i will have a look.

**Comment by andywuest** [comment]
implemented with 0.13.2 - with the next (upcoming) release

**Comment by andywuest** [comment]
fixed with 0.13.2
