### ISSUE TITLE
Dividend calendar fetch aborts with an error

### ISSUE THREAD

**Issue by spodermenpls** [andywuest/harbour-watchlist#109]
As mentioned in the title, since maybe a couple of days, I am no longer able to refresh the dividend calendar on my Sony Xperia XA2 (Watchlist 0.13.2, Sailfish OS 4.5.0.25).

![Bildschirmfoto_20240304_001](https://github.com/andywuest/harbour-watchlist/assets/23747593/df1731d0-53d4-4bb3-990e-7c88c0bc4c51)

**Comment by andywuest** [comment]
I also noticed that problem. API Endpoint is no longer available - i have to switch to a different one. I will have a look at this problem.

**Comment by spodermenpls** [comment]
Thank you very much for your swift work, it works as intended now again.
