### ISSUE TITLE
Icon.

### ISSUE THREAD

**Issue by Okxa** [andywuest/harbour-watchlist#12]
As ApostolosB stated in #10 that he does not intend to modify the icon, I threw something together, because it is a shame if app does not have a icon :)

Took some things you said in the merge request and did this:

![icon-launcher-harbour-watchlist](https://user-images.githubusercontent.com/25027118/74591964-6236ec00-5025-11ea-9672-d7f2254b25ae.png)

If you think this is good, I can push the source file (svg) (and resized appicons too), or upload it somewhere whatever.

**Comment by andywuest** [comment]
Hi, the icon looks very nice. I really like it. looking forward for the pull request.

**Comment by andywuest** [comment]
applied the provided icon - closing issue;
