### ISSUE TITLE
Refresh stock prices on start...

### ISSUE THREAD

**Issue by ApostolosB** [andywuest/harbour-watchlist#37]
.. or at a pre specified interval (5-10-15 min etc.). Or when they change (live) if possible. When i open the app now i have to manually refresh.

**Comment by andywuest** [comment]
I will look what is possible - i am not sure about the intervals - but a refresh on start should be definitely doable.

**Comment by ApostolosB** [comment]
I was mistaken. it actually refreshes stocks on start. 

Closing
