### ISSUE TITLE
Add commodities like gold silver etc

### ISSUE THREAD

**Issue by ApostolosB** [andywuest/harbour-watchlist#45]
As the title suggests. I think euroinvestor lists them.

**Comment by ApostolosB** [comment]
closing this.

**Comment by andywuest** [comment]
well, i have added gold, but i could not find silver, Oil (brent/WTI), or anything else :-(

**Comment by ApostolosB** [comment]
https://www.euroinvestor.dk/markeder/raavarer in this page it lists silver. No idea if this helps.

BTW i think those should be on the same page as the stocks. having separate pages kind of clutters the UI.

**Comment by spodermenpls** [comment]
@andywuest Unfortunately, the precious metals Gold, Silver, Platinum and Palladium no longer get updates in the market data section on my end (last date for Platinum was January, for Gold and Silver in June). I tried removing and re-adding the entries, but now there are only two hyphens shown as placeholders for date and price. Is this just an issue on my end, or did some API change upstream?
