### ISSUE TITLE
Setting of price alert fails to follow locale settings

### ISSUE THREAD

**Issue by zagrim** [andywuest/harbour-watchlist#56]
I just noticed that trying to set a price alert with a decimal number fails if the device locale (number format) doesn't use dot as the decimal separator (in my case, I'm using Finnish locale). The current price is shown correctly (e.g. 3,75€) but trying to set an alert of e.g. 3,5 results in NaN being saved. And since the soft keyboard switches to numbers automatically, there's no way to enter a dot instead of a comma (or maybe there might if I wouldn't be using a built-in keyboard layout, I guess?) To be able to save the alert correctly with a decimal, one needs to paste the dot-formatted number from elsewhere, and be sure to not submit the alert page again since doing that will again corrupt the entry.
Thanks for the app though, and for supporting the SFOS community!

**Comment by andywuest** [comment]
I will try to fix this with the next version.

**Comment by andywuest** [comment]
Is the problem fixed for you now? If so i can close the ticket.

**Comment by zagrim** [comment]
Nope. But there's some oddity with the update to 0.7.2-1 which I think should contain your changes, namely when I updated (and later on, re-installed after removal on the command line for sanity check) to 0.7.2 the About page is still showing "Version 0.7.1", and really I can't know if I'm running the latest version or not. I did `pkcon install harbour-watchlist` after removal and at least based on the package name I'm up-to-date (`pkcon get-details harbour-watchlist` shows 0.7.2-1 as "installed"). Can you please verify if the package is ok and not just 0.7.1 "rebranded" or something like that?
(please note that I'm just a SFOS user, not a developer, so whenever the normal path doesn't work, I'm lost).

**Comment by andywuest** [comment]
I have the same problem. rpm says 0.7.2 - app says 0.7.1. But what i can say is, that the fix did not make it into 0.7.2 - will fix it and release a 0.7.3 later. please test the next version. Thanks.

**Comment by andywuest** [comment]
ok. 0.7.3 is released.

**Comment by zagrim** [comment]
Thanks! Seems to be working now, alert limits are now stored, displayed and work ok.
