### ISSUE TITLE
Prices of very cheap stocks are not displayed

### ISSUE THREAD

**Issue by dikonov** [andywuest/harbour-watchlist#57]
If the price of a stock is so low that it must be expressed with a long decimal fraction, Watchlist cuts off the third and following digits. This makes the price unreadable and the whole display useless. E.g. VTBR at Moscow Exchange is priced at about 0,03502 rouble a piece and mostly fluctuates between 0,03000 and 0,039999. Please, make the app accomodate for the length of fractional prices.

**Comment by andywuest** [comment]
should be fixed with release 0.7.2 - could you please verify? for amounts < 1.0 the app now displays 6 fraction digits;

**Comment by andywuest** [comment]
tested with wirecard - works for me - closing it;
