### ISSUE TITLE
Intraday chart shows 30 day chart

### ISSUE THREAD

**Issue by zagrim** [andywuest/harbour-watchlist#64]
I'm not sure at which update this has been introduced, but the intraday chart seems now to be really showing the 30 day chart. Attached a screenshot of one case. This seems to occur at least with Finnish stocks I have on my list (Euroinvestor backend).

![Screenshot-20201012](https://user-images.githubusercontent.com/25589730/95734449-23c50000-0c8c-11eb-9948-d1a08a9271f8.png)

**Comment by andywuest** [comment]
I will check this - the charts for ing-diba also look strange - always a bad idea to do a refactoring without tests :-(

**Comment by andywuest** [comment]
Charts for other time periods also look strange - corona crash always seems to be way too early in the one/three year charts.

**Comment by zagrim** [comment]
I don't see any problem with the other time periods, the charts match with similar charts taken from an investing information site. Maybe there's something off with just some backends there, I'm looking at data from Euroinvestor.
The labels of the intraday chart are also incorrect, BTW.

With the charts being so little it's a bit difficult to figure out the date/time corresponding to a given point in the graph, though, especially as the x-axis has no grid nor tick marks showing the exact points of the labels. Maybe it would be better to have an option to pop a selected chart to full screen (landscape) at will and have a bit more detailed version of the chart there, as the small charts really can't carry too much information. Maybe I should create a feature request for this :smile:

**Comment by andywuest** [comment]
fixed - closing it.
