### ISSUE TITLE
Error adding stock when trying to add any stock

### ISSUE THREAD

**Issue by zagrim** [andywuest/harbour-watchlist#75]
I'm currently in a situation where no matter which stock I try to add to watchlist (which is empty) results in "Error adding stock" (e.g. Apple or Kone produce this, and the stock exchance of the listing doesn't matter). Market data can be added ok.

I've even tried reinstalling and removing the `.local/share/harbour-watchlist/` directory entirely, but that doesn't help. I ended up noticing this after first having trouble refreshing data from Euroinvestor (I don't know if that was related to #72 or not) and in the process of trying to get things fixed ended up finally also trying out Ing-Diba as backend (now I know it's even less suitable for me than Euroinvestor) which is why I now have empty watchlist.

**Comment by andywuest** [comment]
Which version are you running? Have you installed all updates (regularly)? Which backend are you using (Euroinvestor / Mosocow Exchange / Diba)? when did the version break? with the last update or was the breaking not related to the update?

Can you please start the app from the command line (and redirect the output to a file) and then add a stock to the watchliste -> then please send me the output that was written to the file.

An option would be to reset the database completely - go to the about page there you can find a pully to reset the database - do that. Then try to add stocks again.

**Comment by zagrim** [comment]
Currently I'm running version 0.8.3, and tend to keep my apps up-to-date. Like I told, I was using Euroinvestor when first noticing problems (the initial problem with data refresh reported some error with the API URL mentioned, if I recall correctly). 

According to `/var/log/zypp/history` log, I've installed 0.8.3 on 2021-01-24 but since I hadn't opened the app for quite a while I didn't notice anything before opening it up a few days later and noticing the refresh problem (the last data shown was from November, and 2020-11-08 I had installed in the beginning on November so I might have used the app also with that version, but since I don't recall the exact date of the old data I'm not sure of that).

**Comment by zagrim** [comment]
[watchlist.log](https://github.com/andywuest/harbour-watchlist/files/5899260/watchlist.log)
Attached the log file. Seems like the app is having trouble re-creating the DB. I've also tried the "reset database" action (which I didn't know of before) but that didn't seem to make any difference here.

**Comment by zagrim** [comment]
Anyway, I think we can conclude that I was likely not affected by #72, and the initial problem I had with the data refresh might've been due to SFOS sometimes failing with my Wifi which is fixed simply by reconnecting to it. But before I had thought of that route of resolution, I think I had already made things worse by trying another backend (wiping the watchlist) and/or reinstalling the app and thus hitting the database creation error the logs show.

**Comment by andywuest** [comment]
Strange. Can you remove the sqlite database under  /home/nemo/.local/share/harbour-sailcon/harbour-watchlist/QML/OfflineStorage - and restart the app from the command line and provide the log file? in this case the db should be set up from scratch. i am not sure what happens if you change the db version ( is there a new db created, or only some attribute update) - i had some strange effects when added new column to the tables.

In you log it looks like some db updates have not been executed and the db version is empty- which should not be the case.

**Comment by andywuest** [comment]
think i found the bug. can you please update to 0.8.4 and reset the database again. After that is should be possible to add stocks again.

**Comment by zagrim** [comment]
Thanks, it's working now again!
