### ISSUE TITLE
Curency exchange show no currency symbols.

### ISSUE THREAD

**Issue by ApostolosB** [andywuest/harbour-watchlist#76]
Ie EUR/USD shows 1.20- when it should show something like 1.20 USD or 1.20$

Same goes for other currencies also.

**Comment by andywuest** [comment]
Not sure about that one. can you provide an example? the official page does not show a currency:
https://www.euroinvestor.dk/markeder/valutakurser/eur
another page from germany also shows no currency indiciation:
https://www.finanznachrichten.de/
Same here:
https://www.finanzen.net/
The fact that a "-" is displayed is stupid, i will remove the dash

**Comment by andywuest** [comment]
please retest "-" should be gone with 0.8.6
