### ISSUE TITLE
Refresh of stock prices via ING doesn't work

### ISSUE THREAD

**Issue by spodermenpls** [andywuest/harbour-watchlist#99]
First of all, thank you very much for taking the time to create this app, having a native option for a "Watchlist" type of app, without the need for an Android alternative and its often omnipresent trackers is a great addition to the native app library of Sailfish OS.

Unfortunately I noticed yesterday, that the fetching of current stock prices (I selected ING as source) aborts with the following message:

![Bildschirmfoto_20220502_001](https://user-images.githubusercontent.com/23747593/166414897-c4e25b9c-72a0-46ce-9799-edf7cba12434.png)

Deleting the stock behind the mentioned ISIN doesn't help either, since the fetching error continues with each stock next in line.
Did ING possibly change their API, that would mandate a change inside the app?

Also, on a side note, I am wondering about the functionality of the Dividend section. In your In-App screenshots here on GitHub, a bunch of dividend dates for different stocks are displayed, however the version I use only says that new data needs to be fetched from the Pulley menu (along thoses lines, not a direct quote), however there's no corresponding entry (just "About" and the general "Settings"). Is this feature still work-in-progress, and you just happened to use a screenshot of a yet unpublished beta version, or how can I set up the "dividend calendar" feature?

**Comment by andywuest** [comment]
Sometimes the backend is unavailable, then you get this error -> i tried the URL and it works for me in the normal browser (now) 
https://component-api.wertpapiere.ing.de/api/v1/components/instrumentheader/CH0033361673
Please check again. 

For the dividend feature you need version 0.10.0 and work if you have the Dividends icon next to the Market data and Watchlist icons. Dividends can be update only once a week at the moment, if the last update was < 7 days ago, the pulley option is missing and you have to wait. The UI will only display upcoming dividends of stocks you own, since the list is quite long and it does not make sense to display everyhting. 
In the next release i will relax the update restriction to 3 days, since 7 seems to be a bit long (for me). 
If you still have problems/questions regardings dividens, do not hesitate to ask.

**Comment by spodermenpls** [comment]
@andywuest I just checked again, and the app still throws the same error, now for the third day in a row. I am able to open the link in my browser, too (from the same WiFi connection to the Router). Do you have a hunch what may be wrong with it? If I need to try a re-install, is there possibly some "user settings file" located somewhere, with which I can restore the added Market data and stocks in one swoop, instead of having to add each one by one all over again?

"Stocks you own" means "Stocks added to the watchlist", I assume? Thanks for elaborating, I will keep an eye on it, for now the dividend calendar is still completely empty.

**Comment by andywuest** [comment]
Which stocks do not work? Is this still a problem - can you provide another isin? I also had to remove gazprom, since they have no more prices for that one. Import / export is not (yet) implemented. MyBackup support should be there - but i have never really tested it.

**Comment by spodermenpls** [comment]
@andywuest All of them (more than 20, I guess), everything is stuck on April 29th. I also added a couple of new stocks, but they throw the same error and are listed with no price at all in the list afterwards.

**Comment by spodermenpls** [comment]
@andywuest I finally figured out how to solve it, I just needed to reset the database by changing the source (away from ING and back to it). The watchlist refresh works fine again now.

Re-installing the app was pointless, since the configuration doesn't get deleted during the uninstallation (after the first launch, with the initial permission request, the app is in the same exact state as before). With the help of File Browser, I tried locating Watchlist's config file, but to no avail. The only thing I could find after uninstalling the app by help of search was a 0 Byte file relating to the "Single Instance Lock". The "Apps" section inside the Sailfish Settings only displays the granted permissions, not an option to reset all data or the cache, as one is used to with other installed (Android) apps, either. Am I right in my assumption, that right now there's no way to remove Watchlist without leftovers?

**Comment by andywuest** [comment]
Glad you solved your problem - however it is quite some work to add everyhting again :-( sorry for that. 
I actually did not check the removal process - the securities are stored in the SQL lite database - just like a lot of other apps do this as well. have you checked the my-backup app? I should be supported but i never had the time to test this - configuration (sql database) should be backup there - and i hope it can be found more easily. 

An option would be to add export and import functionality, so we can at least same and restore all your securites....

**Comment by spodermenpls** [comment]
> Glad you solved your problem - however it is quite some work to add everyhting again :-( sorry for that. I actually did not check the removal process - the securities are stored in the SQL lite database - just like a lot of other apps do this as well. have you checked the my-backup app? I should be supported but i never had the time to test this - configuration (sql database) should be backup there - and i hope it can be found more easily.
> 
> An option would be to add export and import functionality, so we can at least same and restore all your securites....

Don't sweat it, re-adding the entries wasn't that much of a hassle due to the auto-completion capability in the search form, having a backup feature would be neat nevertheless. The dividend calendar feature unfortunately is still without function on my end, but I'll move the conversation regarding this to the corresponding Issue.

**Comment by andywuest** [comment]
Hi, 
i found a problem with the dividend tab. Do you get the Pully entry entry to refresh the dividend data? I just noticed, that the initial date was not always properly set - thus the pully entry was not added and a refreshing of the dividend dates was not possible. 
This should be fixed in the next version. If the pully entry is visible - but no dividends show up - we might still have another problem.

**Comment by spodermenpls** [comment]
@andywuest As I've said over here, https://github.com/andywuest/harbour-watchlist/issues/95#issuecomment-1260492328 , I've had a look at the log and I did notice that the initial date was set as "invalid" or something of that nature, in opposite of the log example you provided. This may very well be the culprit.

**Comment by andywuest** [comment]
@spodermenpls  i have uploaded a new version 0.11.1 to openrepos which hopefully fixes the problem.

**Comment by spodermenpls** [comment]
> @spodermenpls i have uploaded a new version 0.11.1 to openrepos which hopefully fixes the problem.

Yes, it worked! For the first time, I could use the manual update feature from the pulley menu, and I have three upcoming dividend payers now in my feed, excellent.

**Comment by andywuest** [comment]
can we close this ticket?

**Comment by spodermenpls** [comment]
> can we close this ticket?

Sure. I'll just notice, from my original issue earlier arose the thought of potentially adding a feature to import/export settings and added entries, that may still be worth of consideration.
